### PR TITLE
Fix/179 Scaling image requests to > or match display scaling and support for hide/show layers

### PR DESCRIPTION
**Pull request by Robbie1977**
- [TBA] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
- [x] Make sure both push and pr travis builds are passing before asking for a review

### CODE REVIEW

**Comment by ddelpiano** [comment]
@Robbie1977 one question, I am pretty sure what I just tested is part of the testing coverage, what is the branch used to deploy this? I would like to double check the jest tests that run at the moment, I am a bit puzzled since this should have been spotted there. Thx

**Comment by Robbie1977** [comment]
@ddelpiano I can't seem to get this error on http://v2-dev2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00015407&i=VFB_00017894 or https://v2.virtualflybrain.org/org.geppetto.frontend/geppetto?id=FBbt_00007453&i=VFB_00017894 which should be using the same code [taken from branch fix/179 into VFBv2.1.0.4 (https://github.com/VirtualFlyBrain/geppetto-vfb/blob/vfb_geppetto_application/Dockerfile#L17)]
image
Although as you can see we have also merged in later PRs fix/184 & fix/177 (1 step back)

**Comment by ddelpiano** [comment]
@Robbie1977 could you rebuild including last fix that Jesus added yesterday to this branch please?

Once we can test this the PR is good to go for me, Jesus explained to me that this issue was visible only on chrome and not firefox and it depends by the way chrome was expressing width and height, since these were handled as decimals the check we have in componentDidUpdate was getting fired like crazy tons of times due to small decimals differences, where on firefox these numbers were rounded to integers (@jrmartin can add more context to this since he worked on the fix).

Regarding the last comment, we were still able to see this issue using the latest geppetto-vfb development and latest geppetto-client with this PR merged inside, not sure why on v2-dev2 you were not able to reproduce it but this should fix it once for all.
Thx!

**Comment by Robbie1977** [comment]
@ddelpiano FYI that would be the issue https://github.com/VirtualFlyBrain/geppetto-vfb/blob/vfb_geppetto_application/Dockerfile#L17

**Comment by Robbie1977** [comment]
Merged fix/179 into v .5 and rebuilding https://travis-ci.org/github/VirtualFlyBrain/geppetto-vfb/builds/672591740

**Comment by Robbie1977** [comment]
@ddelpiano can you see if you can replicate the error in v2-dev2 now?

**Comment by ddelpiano** [comment]
@gidili @tarelli this can go for me, tested as discussed at one geppetto meeting in the past. Thx

**Pull request merged**
