### PR TITLE
Feature/124

### PR DESCRIPTION
**Pull request by Robbie1977**
- [another ticket] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
- [x] Make sure both push and pr travis builds are passing before asking for a review

# Adding float over labelling to StackViewer https://github.com/openworm/geppetto-client/issues/124
Adding the float over-identification following the mouse pointer

### CODE REVIEW

**Comment by Robbie1977** [comment]
https://github.com/openworm/geppetto-client/pull/125/files#diff-0a1e5757b508f99c409aaeb43755226aL446-R472
Is simply removing the check to see if the mouse has moved since the request was made which is no longer needed as the label is placed by the coordinates of the original request.

**Comment by Robbie1977** [comment]
https://github.com/openworm/geppetto-client/pull/125/files#diff-0a1e5757b508f99c409aaeb43755226aR893-R902 
Status Text appears on the top left as before but hover-over identification is placed to the bottom right of the cursor.

**Comment by Robbie1977** [comment]
Closes https://github.com/VirtualFlyBrain/geppetto-vfb/issues/198

**Comment by Robbie1977** [comment]
resolves https://github.com/VirtualFlyBrain/VFB2/issues/110

**Comment by Robbie1977** [comment]
resolves https://github.com/VirtualFlyBrain/VFB2/issues/71

**Comment by Robbie1977** [comment]
resolves https://github.com/VirtualFlyBrain/VFB2/issues/70

**Comment by Robbie1977** [comment]
resolves #124

**Comment by ddelpiano** [comment]
@Robbie1977 @tarelli I am currently testing this from vfb_geppetto_application (as robb suggested since this is the latest deployed and the label issue is resolved).
@Robbie1977 I can see some differences between this and vfb_geppetto_application, can we re-align this with vfb_geppetto_application (where I can see the labels working) so we can approve the merge? (if you are busy let me know and I can do this).
Thx!

**Comment by Robbie1977** [comment]
@ddelpiano @tarelli This is ready to go now.

**Comment by Robbie1977** [comment]
@tarelli @ddelpiano Can we get this one merged?

**Comment by tarelli** [comment]
@Robbie1977 done, still hadn't had a chance to catch up with all PRs!

**Pull request merged**
